name: CI

on:
  push:
    branches:    # Array of patterns that match refs/heads
    - gh-pages     # Push events on master branch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 10.x
      - name: npm install, build, and test
      run: |
        git remote set-url origin https://${secrets.TEST_TOKEN}@github.com/${GITHUB_REPOSITORY}
        npm install
        npm run md
        npm run generate & npx gh-pages -d dist -t -branch master
      env:
        CI: true
